<a href="https://colab.research.google.com/github/davidmungai/python-udemy-bootcamp/blob/main/torch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torchvision 

In [ ]:
import torch

In [ ]:
torch.FloatTensor([[20, 30, 40], [90, 60, 70]])

tensor([[20., 30., 40.],
        [90., 60., 70.]])

If you’re using a GPU-enabled machine, you’ll define the tensor as shown below:



In [ ]:
torch.cuda.FloatTensor([[20, 30, 40], [90, 60, 70]])


tensor([[20., 30., 40.],
        [90., 60., 70.]], device='cuda:0')

Addition in pytorch tensors

In [ ]:
x = torch.FloatTensor([25])
y = torch.FloatTensor([30])
x + y

tensor([55.])

Let’s see how you’d define a matrix and transpose it:

In [ ]:
matrix = torch.randn(4, 5)
print(matrix)
matrix.t()

tensor([[ 1.6269,  0.5325,  1.7139,  1.8068,  2.1578],
        [-1.7629, -0.1990,  1.0698,  0.8328, -1.2295],
        [ 0.2821,  0.6284,  2.1060,  0.1706,  0.5039],
        [ 0.1907, -0.5336, -1.0446,  0.0430,  0.1782]])


tensor([[ 1.6269, -1.7629,  0.2821,  0.1907],
        [ 0.5325, -0.1990,  0.6284, -0.5336],
        [ 1.7139,  1.0698,  2.1060, -1.0446],
        [ 1.8068,  0.8328,  0.1706,  0.0430],
        [ 2.1578, -1.2295,  0.5039,  0.1782]])

In [ ]:
a = torch.tensor([3.0, 2.0], requires_grad=True)
b = torch.tensor([4.0, 7.0])
ab_sum = a + b
ab_sum
ab_res = (ab_sum*8).sum()
ab_res.backward()
ab_res
a.grad

tensor([8., 8.])

PyTorch nn Module
 
This is the module for building neural networks in PyTorch. nn depends on autograd to define models and differentiate them. Let’s start by defining the procedure for training a neural network:

Define the neural network with some learnable parameters, referred to as weights.
Iterate over a dataset of inputs.
Process input through the network.
Compare predicted results to actual values and measure the error.
Propagate gradients back into the network’s parameters.
Update the weights of the network using a simple update rule:
weight = weight — learning_rate * gradient

You’ll now use the nn package to create a two-layer neural network:

In [ ]:
N, D_in, H, D_out = 64, 1000, 100, 10
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)
model = torch.nn.Sequential(
torch.nn.Linear(D_in, H),
torch.nn.ReLU(),
torch.nn.Linear(H, D_out),
)
loss_fn = torch.nn.MSELoss()
learning_rate = 1e-4

Let’s explain some of the parameters used above:

N is batch size. Batch size is the number of observations after which the weights will be updated.
D_in is the input dimension
H is the hidden dimension
D_out is the output dimension
torch.randn defines a matrix of the specified dimensions
torch.nn.Sequential initializes a linear stack of layers
torch.nn.Linear applies a linear transformation to the incoming data
torch.nn.ReLU applies the rectified linear unit function element-wise
torch.nn.MSELoss creates a criterion that measures the mean squared error between n elements in the input x and target y


In [ ]:
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
for t in range(500):
  y_pred = model(x)
  loss = loss_fn(y_pred, y)
  print(t, loss.item())
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

0 1.1983904838562012
1 1.1695210933685303
2 1.1413344144821167
3 1.1139384508132935
4 1.0873816013336182
5 1.0615686178207397
6 1.0364868640899658
7 1.0122922658920288
8 0.9887479543685913
9 0.9658439755439758
10 0.9436478614807129
11 0.9219928979873657
12 0.9010076522827148
13 0.880699634552002
14 0.8610265851020813
15 0.8418775796890259
16 0.823326587677002
17 0.8052374124526978
18 0.7876085042953491
19 0.7703875303268433
20 0.7535830736160278
21 0.7373460531234741
22 0.7215113043785095
23 0.7061861753463745
24 0.6912368535995483
25 0.676653265953064
26 0.6624200940132141
27 0.6484655141830444
28 0.6348663568496704
29 0.6216282844543457
30 0.6086676716804504
31 0.5960590839385986
32 0.5838258266448975
33 0.5719012022018433
34 0.5602949857711792
35 0.5489459037780762
36 0.5378645062446594
37 0.527021050453186
38 0.5164378881454468
39 0.5060321092605591
40 0.49578267335891724
41 0.48572421073913574
42 0.4758778214454651
43 0.4661885201931
44 0.45670634508132935
45 0.44737571477890015
4